version: "3.7"

services:
  finwa-backend:
    image: deryeger/finwa-backend
    env_file:
      - ./docker/environment/finwa.env
    ports:
      - 8080:8080
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - finwa-network
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - finwa-network

networks:
  finwa-network:
