version: "3.7"

services:
  finwa-backend:
    image: deryeger/finwa-backend
    env_file:
      - ./docker/environments/domain.env
      - ./docker/environments/finwa.env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - finwa-network
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - finwa-network
  letsencrypt:
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    env_file:
      - ./docker/environments/domain.env
      - ./docker/environments/letsencrypt.env
    ports:
      - 443:443
      - 80:80
    volumes:
      - type: bind
        source: ./docker/nginx/finwa.subfolder.conf
        target: /config/nginx/proxy-confs/finwa.subfolder.conf
        read_only: true
    restart: unless-stopped
    networks:
      - finwa-network

networks:
  finwa-network:
